<?php

namespace App;

use Laratrust\Models\LaratrustRole;

/**
 * Class Role (generated by Laratrust)
 *
 * @package App\Models
 */
class Role extends LaratrustRole
{

    /**
     * The primary key of the 'roles' table associated with the Role entity.
     *
     * @var string
     */
    protected $primaryKey = 'role_id';

    /**
     * The restricted attributes for mass-assignment.
     *
     * @var array
     */
    protected $guarded = [];
}
